spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/accident_db?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

app:
  python:
    exec: "C:/Users/1/Accident-Predict-Project/.venv1/Scripts/python.exe"       # venv python
    script: "C:/Users/1/Accident-Predict-Project/python/infer_cli.py"           # 위 스크립트 경로
    scaler: "C:/Users/1/Accident-Predict-Project/python/models/scaler.pkl"      # scaler.pkl
    model: "C:/Users/1/Accident-Predict-Project/python/models/fcast.h5"     # fcast.h5
  cors:
    origins:
      - http://localhost:3000
      - http://localhost:8000
    allow-credentials: true
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    exposed-headers:
      - Content-Disposition

  management:
    endpoints:
      web:
        exposure:
          include: health,info,mappings
    endpoint:
      health:
        show-details: always